SELECT * FROM office.EMPLOYEES
SELECT * FROM office.DEPARTMENTS

---FINDING DUPLICATES---
SELECT EMPLOYEE_NAME,DEPARTMENT_ID,GENDER,SALARY,HIRE_DATE,COUNT(1) 
AS DUPLICATE 
FROM office.EMPLOYEES
GROUP BY EMPLOYEE_NAME,DEPARTMENT_ID,GENDER,SALARY,HIRE_DATE
HAVING COUNT(1)>1

---REMOVE DUPLICATE---

WITH cte AS (
    SELECT EMPLOYEE_NAME,DEPARTMENT_ID,GENDER,SALARY,HIRE_DATE,
    DENSE_RANK() OVER (
        PARTITION BY EMPLOYEE_NAME,DEPARTMENT_ID,GENDER,SALARY,HIRE_DATE
        ORDER BY EMPLOYEE_ID)
    AS rn
    FROM office.EMPLOYEES
)
DELETE FROM cte WHERE rn > 1;
GO



---MISSING DATA---
SELECT * FROM office.EMPLOYEES 
WHERE EMPLOYEE_ID IS NULL OR 
EMPLOYEE_NAME IS NULL 
OR DEPARTMENT_ID IS NULL 
OR GENDER IS NULL OR ISNULL(GENDER,'')='' OR SALARY IS NULL
OR HIRE_DATE IS NULL

---DEALING WITH MISSING VALUES---
UPDATE office.EMPLOYEES SET DEPARTMENT_ID = 2 WHERE EMPLOYEE_ID=8
UPDATE office.EMPLOYEES SET GENDER = 'F' WHERE EMPLOYEE_ID IN(9,14)

---UNIFORMING GENDER REPRESENTATION---
UPDATE office.EMPLOYEES SET GENDER=
CASE 
WHEN UPPER(GENDER) IN('M','MALE') THEN 'M'
WHEN UPPER(GENDER) IN('F','FEMALE') THEN 'F'
ELSE ''
END


---TYPE CONVERSION---
---SALARY is varchar type due to which numeric operations like SUM,AVG etc cannot be done---
--PERMANENT SOLUTION--
ALTER TABLE office.EMPLOYEES
ALTER COLUMN SALARY INT
---TEMPORARY SOLUTION---
SELECT d.DEPARTMENT_NAME,AVG(CAST(SALARY AS DECIMAL(9,2))) AS 'AVERAGE SALARY' FROM office.EMPLOYEES e
LEFT JOIN office.DEPARTMENTS d
ON d.DEPARTMENT_ID = e.DEPARTMENT_ID
GROUP BY d.DEPARTMENT_NAME